apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-mart-deployment
  labels:
    app: mobile-mart
spec:
  replicas: 1
  selector:
    matchLabels:
      process: program
  template:
    metadata:
      labels:
        process: program
    spec:
      containers:
        - name: mobile-mart
          image: vajidhussain/mobile-mart
          ports:
            - containerPort: 7000
            
---

apiVersion: v1
kind: Service
metadata:
  name: mobilemart-service
spec:
  type: NodePort
  ports:
    - targetPort: 7000
      port: 7000
      nodePort: 30007
  selector:
    process: program
