apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    db: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      database: postgres
  template:
    metadata:
      name: postgres-pod
      labels:
        database: postgres
    spec:
      containers:
        - name: database
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: dbpassword                                                        

---

apiVersion: v1
kind: Service
metadata:
  name: postgresdb
spec:
  type: ClusterIP
  selector:
    database: postgres
  ports:
    - port: 5432
      targetPort: 5432
